# PersonDistance.msg

DetectedPersons detected_persons
float32[] distances
float32[] real_world_coordinates 

# all the x,y,z values for all bodyparts detected on the image
float32[] nose_real_world_coordinates
float32[] left_eye_real_world_coordinates
float32[] right_eye_real_world_coordinates
float32[] left_ear_real_world_coordinates
float32[] right_ear_real_world_coordinates
float32[] left_shoulder_real_world_coordinates
float32[] right_shoulder_real_world_coordinates
float32[] left_elbow_real_world_coordinates
float32[] right_elbow_real_world_coordinates
float32[] left_wrist_real_world_coordinates
float32[] right_wrist_real_world_coordinates
float32[] left_hip_real_world_coordinates
float32[] right_hip_real_world_coordinates
float32[] left_knee_real_world_coordinates
float32[] right_knee_real_world_coordinates
float32[] left_ankle_real_world_coordinates
float32[] right_ankle_real_world_coordinates